chore: reduce verbosity in output
vaadin/skeleton-starter-flow-spring pull request #869
Opened 2022-10-05 12:18 UTC by manolo

2022-10-05 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/skeleton-starter-flow-spring?pullRequest=869) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/skeleton-starter-flow-spring?pullRequest=869) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/skeleton-starter-flow-spring?pullRequest=869) it.</sub>

2022-10-05 12:21 UTC, Artur- requested changes
Wouldn't it be more appropriate to not log the debug level?

2022-10-05 12:34 UTC, manolo commented
@Artur- I already tested this with a `logback-test.xml`, and it logs a lot of useless information.

Note, that still sending the output to file, in case of failure, the exception with all the meaningful information is displayed in the console, and the user still has the full output in the `target/failsafe-reports/`


**logback configuration**
```
<configuration>
  <include resource="/org/springframework/boot/logging/logback/base.xml"/>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
      </pattern>
    </encoder>
  </appender>
  <root level="INFO">
    <appender-ref ref="STDOUT"/>
  </root>
</configuration>
```

**output with logback configured**

```
>>> 14:28:59,163 [INFO]
>>> 14:28:59,163 [INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ spring-skeleton ---
>>> 14:28:59,248 [INFO]
>>> 14:28:59,248 [INFO] -------------------------------------------------------
>>> 14:28:59,248 [INFO]  T E S T S
>>> 14:28:59,248 [INFO] -------------------------------------------------------
14:28:59,809 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/Users/manolo/Github/platform/platform-in-test-script/tmp/skeleton-starter-flow-spring/target/test-classes/logback-test.xml]
14:28:59,854 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:28:59,857 |-WARN in ch.qos.logback.core.joran.action.IncludeAction - Could not find resource corresponding to [/org/springframework/boot/logging/logback/base.xml]
14:28:59,858 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:28:59,859 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:28:59,863 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:28:59,904 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:28:59,904 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:28:59,905 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:28:59,905 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@70e9c95d - Registering current configuration as safe fallback point

>>> 14:29:00,193 [INFO] Running org.vaadin.example.MainViewIT
14:29:00.453 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using chromedriver 105.0.5195.52 (resolved driver for Chrome 105)
14:29:00.484 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /Users/manolo/.cache/selenium/chromedriver/mac64/105.0.5195.52/chromedriver
Starting ChromSteaSStStarting ChrrtDinotartinagm Cg CrivehheDrirverrrS 1oomeDriver 10r 105.0.5195.52t ing5meDriver 105.0.5105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#tarting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs853}) on port 61656
Only local connections are95.52 (412c95e518836d8.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-re ChromeDriver 105.0.5195.52 (412c(412c95e518836d8a7d9795efsa al/bralo7d97250d/b518250d683r6anwench-d.
ch-heads/512b29c2ae6a266d8a27b29a85-9P5lease sheee@{#853})refc2d972ae6s/branch-he o httadsps:/n pads/51a2650a8595@{#8o53}) on port/c/5hromedrive 50166
rt 55-3red6fs/15Only local conr.19chnec
Onbr2b29anlytiorom5@{iuns  local ch-heads/519c2ae6a26a85-r5@{#853connecarem.o#85rg/3})  ations are})efs/br on por allon posecurrtowleldt anch-h588.
Pow 6it2435
ed.le00
eaOnlyase
PleaseOny-ly l sse lds/5oce hee hotcal conconnetpts:/al 19connectio/chtpsctsiderions :/romedrins are5@ aver.chromium.or/chromare aatilloweedg/secull{#owedrityrivd.ons
Per.-con.
853}) on porPlsiderachlefor ase rotionseast 51e see https://chromedriver.chro formium.mium.org/sseesu hteorg su714
Oggecur/setpggestions://chcuity-stnly ioncority-ros omedrivconsiders localon ations fonseiderr.chrn keeomium.atir suggeke cepistions onons for suggestions oorpingg/sn  kng onnectioCnhromeDeepkeeec Curity-coping Chinriver safs aree.g ChromeDriver safe.
ChromeDriver was startronhromeDsrivmeed
 s Chrallowed.ucceDriver er saidefe.
saCss
PlomeDreafuhromeDfe.
rCahromriver walsle seiver was stare y.s staeDrtioiverted
htted suctps: sur ns wacc//chcessfully.
roessfuls for sustgagrtlymedri.
ed sucecsvetions essfon keeping r.chromiuChromeDullyrivem.org/security-consir.
 sdeafe.rations
foCr hrsuomeDggriver wesas tions osnt keepiartengd su Chccesrosfulmely.
Driver safe.
ChromeDriver was started successfully.
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Oct 05, 2022 2:29:04 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:04 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
Oct 05, 2022 2:29:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:04 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:04 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
2022-10-05 14:29:04.484  INFO 22605 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-10-05 14:29:04.484  INFO 22605 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-10-05 14:29:04.484  INFO 22605 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2022-10-05 14:29:04.532  INFO 22605 --- [nio-8080-exec-1] c.vaadin [...]

2022-10-06 07:01 UTC, manolo commented
changed the PR so as the user still can see the output in console by adding the parameter `-Dmaven.test.redirectTestOutputToFile=true` to `mvn`

2022-10-07 07:10 UTC, ZheSun88 approved these changes

2022-10-07 13:30 UTC, Artur- approved these changes

2022-10-07 13:30 UTC, merged